/**
 * @author khiemnd
 * @flow
 */

const images = {
  avatar: require('../assets/images/avatar.png'),
  bootsplash_logo: require('../assets/images/bootsplash_logo.png'),
  empty_folder: require('../assets/images/empty_folder.png'),
  eye: require('../assets/images/eye.png'),
  favourite: require('../assets/images/favourite.png'),
  flag: require('../assets/images/flag.png'),
  home_bg: require('../assets/images/home-bg.png'),
  ic_arrow_down: require('../assets/images/ic_arrow_down.png'),
  ic_arrow_right: require('../assets/images/ic_arrow_right.png'),
  ic_back: require('../assets/images/ic_back.png'),
  ic_calender: require('../assets/images/ic_calender.png'),
  ic_checkIn: require('../assets/images/ic_checkIn.png'),
  ic_checkOut: require('../assets/images/ic_checkOut.png'),
  ic_close: require('../assets/images/ic_close.png'),
  ic_comment: require('../assets/images/ic_comment.png'),
  ic_dropdown: require('../assets/images/ic_dropdown.png'),
  ic_food: require('../assets/images/ic_food.png'),
  ic_hightlight: require('../assets/images/ic_hightlight.png'),
  ic_hotel: require('../assets/images/ic_hotel.png'),
  ic_library: require('../assets/images/ic_library.png'),
  ic_like: require('../assets/images/ic_like.png'),
  ic_location: require('../assets/images/ic_location.png'),
  ic_location_map: require('../assets/images/ic_location_map.png'),
  ic_map: require('../assets/images/ic_map.png'),
  ic_name: require('../assets/images/ic_name.png'),
  ic_note: require('../assets/images/ic_note.png'),
  ic_pen: require('../assets/images/ic_pen.png'),
  ic_pen_edit: require('../assets/images/ic_pen_edit.png'),
  ic_phone: require('../assets/images/ic_phone.png'),
  ic_quantity_person: require('../assets/images/ic_quantity_person.png'),
  ic_share: require('../assets/images/ic_share.png'),
  ic_Star: require('../assets/images/ic_Star.png'),
  ic_tour: require('../assets/images/ic_tour.png'),
  ic_VR: require('../assets/images/ic_VR.png'),
  img1: require('../assets/images/img1.png'),
  img2: require('../assets/images/img2.png'),
  item: require('../assets/images/item.png'),
  item2: require('../assets/images/item2.png'),
  item3: require('../assets/images/item3.png'),
  login: require('../assets/images/login.png'),
  logo: require('../assets/images/logo.png'),
  menubgr: require('../assets/images/menubgr.png'),
  noImage: require('../assets/images/noImage.png'),
  nonfavourite: require('../assets/images/nonfavourite.png'),
  opt_bg: require('../assets/images/opt-bg.png'),
  star: require('../assets/images/star.png'),
  Subtract: require('../assets/images/Subtract.png'),
  success: require('../assets/images/success.png'),
  VietNam: require('../assets/images/VietNam.png'),
};
export default images;
